### ISSUE TITLE
Navigation Error on Azure Static  Web Site

### ISSUE THREAD

**Issue by kerrpeter** [GamerRaven/Wyvern-Team-Portfolio#2]
I'm deploying this to Azure Static Web Site.

I added the following staticwebapp.config.json file at the root
`{
  "navigationFallback": {
    "rewrite": "index.html",
    "exclude": ["/static/media/*.{png,jpg,jpeg,gif,bmp}", "/static/css/*"]
  },
  "mimeTypes": {
    ".json": "text/json"
  }
}
`
But when I go to terms & Conditions I get 4040 Not found.
Can you tell me what should be configured for this with Azure Static web site

**Comment by kerrpeter** [comment]
The only way I could get this to work was using the Redirect Rule in Azure Front Door
see [here](https://antbutcher.medium.com/hosting-a-react-js-app-on-azure-blob-storage-azure-cdn-for-ssl-and-routing-8fdf4a48feeb#1204)

**Comment by jimmywang585** [comment]
Hello there @kerrpeter. Unfortunely I do not have knowledge with Microsoft Azure Static Web Apps, and therefore I cannot guarantee that I can assist you with this. 

However, check if the public folder was uploaded to the container.

**Comment by jimmywang585** [comment]
The public folder should be added to the root directory of the server.
